# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tunnel_pb2 as tunnel__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tunnel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TunnelServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enroll = channel.unary_unary(
                '/noderouter.tunnel.v1.TunnelService/Enroll',
                request_serializer=tunnel__pb2.EnrollRequest.SerializeToString,
                response_deserializer=tunnel__pb2.EnrollResponse.FromString,
                _registered_method=True)
        self.Tunnel = channel.stream_stream(
                '/noderouter.tunnel.v1.TunnelService/Tunnel',
                request_serializer=tunnel__pb2.RunnerFrame.SerializeToString,
                response_deserializer=tunnel__pb2.CoreFrame.FromString,
                _registered_method=True)


class TunnelServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Enroll(self, request, context):
        """Enroll registers (or re-registers) a runner and issues its client cert.

        Served on the plaintext enroll port. Request metadata:
        x-noderouter-ts:  unix timestamp (seconds, string)
        x-noderouter-sig: "sha256=" + hex(HMAC-SHA256(RUNNER_SECRET,
        "{ts}\n{name}\n{sha256hex(csr_pem)}"))
        The response carries its own HMAC (response_sig) so a plaintext channel
        cannot be tampered with: hex(HMAC-SHA256(RUNNER_SECRET,
        "{node_id}\n{sha256hex(client_cert_pem)}\n{sha256hex(ca_cert_pem)}"))
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tunnel(self, request_iterator, context):
        """Tunnel is the persistent bidirectional frame stream.
        Served on the mTLS port; identity = verified client cert CN (node_id).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TunnelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=tunnel__pb2.EnrollRequest.FromString,
                    response_serializer=tunnel__pb2.EnrollResponse.SerializeToString,
            ),
            'Tunnel': grpc.stream_stream_rpc_method_handler(
                    servicer.Tunnel,
                    request_deserializer=tunnel__pb2.RunnerFrame.FromString,
                    response_serializer=tunnel__pb2.CoreFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'noderouter.tunnel.v1.TunnelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('noderouter.tunnel.v1.TunnelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TunnelService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noderouter.tunnel.v1.TunnelService/Enroll',
            tunnel__pb2.EnrollRequest.SerializeToString,
            tunnel__pb2.EnrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tunnel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/noderouter.tunnel.v1.TunnelService/Tunnel',
            tunnel__pb2.RunnerFrame.SerializeToString,
            tunnel__pb2.CoreFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
